# Generated by Django 5.1.5 on 2025-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
