# Generated by Django 5.1.5 on 2025-02-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_options_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Описание для SEO', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='articles',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова для SEO', max_length=250, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='articles',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок для SEO', max_length=70, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='discr',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
