# Generated by Django 5.1.5 on 2025-02-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_meta_description_articles_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Размещена'),
        ),
    ]
