# Generated by Django 5.1.5 on 2025-02-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='is_published',
        ),
    ]
