# Generated by Django 5.1.5 on 2025-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/articles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
    ]
