# Generated by Django 5.1.5 on 2025-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_image_alter_subscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_webp',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='img/articles/', verbose_name='Изображение WebP'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Описание для SEO', max_length=180, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок для SEO', max_length=75, verbose_name='Meta Title'),
        ),
    ]
