# Generated by Django 5.1.5 on 2025-02-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_image_webp_alter_articles_meta_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image_webp',
        ),
    ]
