# Generated by Django 5.1.5 on 2025-08-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_delete_subscription_remove_articles_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='img/articles/', verbose_name='WebP изображение'),
        ),
    ]
