# Generated by Django 5.1.5 on 2025-08-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articles_image_webp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image_webp',
        ),
    ]
