# Конфигурация городов для Expertsmet
# Все настройки городов в одном месте

CITIES_DATA = {
    'moscow': {
        'name': 'Москва',
        'name_prep': 'Москве',
        'subdomain': 'moscow',
        'url': 'https://moscow.expertsmet.ru',
        'template_folder': 'moscow',
        'phone': '+7 (917) 565-46-16',
        'email': 'moscow@expertsmet.ru',
        'address': 'г. Москва, Шелепихинская наб., 34к6',
        'timezone': 'Europe/Moscow',
        'is_main': True,
        'order': 1,
    },
    'spb': {
        'name': 'Санкт-Петербург',
        'name_prep': 'Санкт-Петербурге',
        'subdomain': 'spb', 
        'url': 'https://spb.expertsmet.ru',
        'template_folder': 'spb',
        'phone': '+7 (917) 565-46-16',
        'email': 'spb@expertsmet.ru',
        'address': 'г. Санкт-Петербург, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 2,
    },
    'ekaterinburg': {
        'name': 'Екатеринбург',
        'name_prep': 'Екатеринбурге',
        'subdomain': 'ekaterinburg',
        'url': 'https://ekaterinburg.expertsmet.ru', 
        'template_folder': 'ekaterinburg',
        'phone': '+7 (917) 565-46-16',
        'email': 'ekaterinburg@expertsmet.ru',
        'address': 'г. Екатеринбург, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 3,
    },
    'novosibirsk': {
        'name': 'Новосибирск',
        'name_prep': 'Новосибирске',
        'subdomain': 'novosibirsk',
        'url': 'https://novosibirsk.expertsmet.ru',
        'template_folder': 'novosibirsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'novosibirsk@expertsmet.ru',
        'address': 'г. Новосибирск, ул. Примерная, д. 1',
        'timezone': 'Asia/Novosibirsk',
        'is_main': False,
        'order': 4,
    },
    'nizhny-novgorod': {
        'name': 'Нижний Новгород',
        'name_prep': 'Нижнем Новгороде',
        'subdomain': 'nizhny-novgorod',
        'url': 'https://nizhny-novgorod.expertsmet.ru',
        'template_folder': 'nizhny-novgorod',
        'phone': '+7 (917) 565-46-16',
        'email': 'nizhny@expertsmet.ru',
        'address': 'г. Нижний Новгород, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 5,
    },
    'kazan': {
        'name': 'Казань',
        'name_prep': 'Казани',
        'subdomain': 'kazan',
        'url': 'https://kazan.expertsmet.ru',
        'template_folder': 'kazan',
        'phone': '+7 (917) 565-46-16',
        'email': 'kazan@expertsmet.ru',
        'address': 'г. Казань, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 6,
    },
    'chelyabinsk': {
        'name': 'Челябинск',
        'name_prep': 'Челябинске',
        'subdomain': 'chelyabinsk',
        'url': 'https://chelyabinsk.expertsmet.ru',
        'template_folder': 'chelyabinsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'chelyabinsk@expertsmet.ru',
        'address': 'г. Челябинск, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 7,
    },
    'krasnodar': {
        'name': 'Краснодар',
        'name_prep': 'Краснодаре',
        'subdomain': 'krasnodar',
        'url': 'https://krasnodar.expertsmet.ru',
        'template_folder': 'krasnodar',
        'phone': '+7 (917) 565-46-16',
        'email': 'krasnodar@expertsmet.ru',
        'address': 'г. Краснодар, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 8,
    },
    'krasnoyarsk': {
        'name': 'Красноярск',
        'name_prep': 'Красноярске',
        'subdomain': 'krasnoyarsk',
        'url': 'https://krasnoyarsk.expertsmet.ru',
        'template_folder': 'krasnoyarsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'krasnoyarsk@expertsmet.ru',
        'address': 'г. Красноярск, ул. Примерная, д. 1',
        'timezone': 'Asia/Krasnoyarsk',
        'is_main': False,
        'order': 9,
    },
    'perm': {
        'name': 'Пермь',
        'name_prep': 'Перми',
        'subdomain': 'perm',
        'url': 'https://perm.expertsmet.ru',
        'template_folder': 'perm',
        'phone': '+7 (917) 565-46-16',
        'email': 'perm@expertsmet.ru',
        'address': 'г. Пермь, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 10,
    },
    'rostov': {
        'name': 'Ростов-на-Дону',
        'name_prep': 'Ростове-на-Дону',
        'subdomain': 'rostov',
        'url': 'https://rostov.expertsmet.ru',
        'template_folder': 'rostov',
        'phone': '+7 (917) 565-46-16',
        'email': 'rostov@expertsmet.ru',
        'address': 'г. Ростов-на-Дону, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 11,
    },
    'samara': {
        'name': 'Самара',
        'name_prep': 'Самаре',
        'subdomain': 'samara',
        'url': 'https://samara.expertsmet.ru',
        'template_folder': 'samara',
        'phone': '+7 (917) 565-46-16',
        'email': 'samara@expertsmet.ru',
        'address': 'г. Самара, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 12,
    },
    'tyumen': {
        'name': 'Тюмень',
        'name_prep': 'Тюмени',
        'subdomain': 'tyumen',
        'url': 'https://tyumen.expertsmet.ru',
        'template_folder': 'tyumen',
        'phone': '+7 (917) 565-46-16',
        'email': 'tyumen@expertsmet.ru',
        'address': 'г. Тюмень, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 13,
    },
    'ufa': {
        'name': 'Уфа',
        'name_prep': 'Уфе',
        'subdomain': 'ufa',
        'url': 'https://ufa.expertsmet.ru',
        'template_folder': 'ufa',
        'phone': '+7 (917) 565-46-16',
        'email': 'ufa@expertsmet.ru',
        'address': 'г. Уфа, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 14,
    },
    'volgograd': {
        'name': 'Волгоград',
        'name_prep': 'Волгограде',
        'subdomain': 'volgograd',
        'url': 'https://volgograd.expertsmet.ru',
        'template_folder': 'volgograd',
        'phone': '+7 (917) 565-46-16',
        'email': 'volgograd@expertsmet.ru',
        'address': 'г. Волгоград, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 15,
    },
    'omsk': {
        'name': 'Омск',
        'name_prep': 'Омске',
        'subdomain': 'omsk',
        'url': 'https://omsk.expertsmet.ru',
        'template_folder': 'omsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'omsk@expertsmet.ru',
        'address': 'г. Омск, ул. Примерная, д. 1',
        'timezone': 'Asia/Omsk',
        'is_main': False,
        'order': 16,
    },
    'voronezh': {
        'name': 'Воронеж',
        'name_prep': 'Воронеже',
        'subdomain': 'voronezh',
        'url': 'https://voronezh.expertsmet.ru',
        'template_folder': 'voronezh',
        'phone': '+7 (917) 565-46-16',
        'email': 'voronezh@expertsmet.ru',
        'address': 'г. Воронеж, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 17,
    },
    'saratov': {
        'name': 'Саратов',
        'name_prep': 'Саратове',
        'subdomain': 'saratov',
        'url': 'https://saratov.expertsmet.ru',
        'template_folder': 'saratov',
        'phone': '+7 (917) 565-46-16',
        'email': 'saratov@expertsmet.ru',
        'address': 'г. Саратов, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 18,
    },
    'irkutsk': {
        'name': 'Иркутск',
        'name_prep': 'Иркутске',
        'subdomain': 'irkutsk',
        'url': 'https://irkutsk.expertsmet.ru',
        'template_folder': 'irkutsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'irkutsk@expertsmet.ru',
        'address': 'г. Иркутск, ул. Примерная, д. 1',
        'timezone': 'Asia/Irkutsk',
        'is_main': False,
        'order': 19,
    },
    'novokuznetsk': {
        'name': 'Новокузнецк',
        'name_prep': 'Новокузнецке',
        'subdomain': 'novokuznetsk',
        'url': 'https://novokuznetsk.expertsmet.ru',
        'template_folder': 'novokuznetsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'novokuznetsk@expertsmet.ru',
        'address': 'г. Новокузнецк, ул. Примерная, д. 1',
        'timezone': 'Asia/Krasnoyarsk',
        'is_main': False,
        'order': 20,
    },
    'barnaul': {
        'name': 'Барнаул',
        'name_prep': 'Барнауле',
        'subdomain': 'barnaul',
        'url': 'https://barnaul.expertsmet.ru',
        'template_folder': 'barnaul',
        'phone': '+7 (917) 565-46-16',
        'email': 'barnaul@expertsmet.ru',
        'address': 'г. Барнаул, ул. Примерная, д. 1',
        'timezone': 'Asia/Barnaul',
        'is_main': False,
        'order': 21,
    },
    'belgorod': {
        'name': 'Белгород',
        'name_prep': 'Белгороде',
        'subdomain': 'belgorod',
        'url': 'https://belgorod.expertsmet.ru',
        'template_folder': 'belgorod',
        'phone': '+7 (917) 565-46-16',
        'email': 'belgorod@expertsmet.ru',
        'address': 'г. Белгород, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 22,
    },
    'bryansk': {
        'name': 'Брянск',
        'name_prep': 'Брянске',
        'subdomain': 'bryansk',
        'url': 'https://bryansk.expertsmet.ru',
        'template_folder': 'bryansk',
        'phone': '+7 (917) 565-46-16',
        'email': 'bryansk@expertsmet.ru',
        'address': 'г. Брянск, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 23,
    },
    'ivanovo': {
        'name': 'Иваново',
        'name_prep': 'Иванове',
        'subdomain': 'ivanovo',
        'url': 'https://ivanovo.expertsmet.ru',
        'template_folder': 'ivanovo',
        'phone': '+7 (917) 565-46-16',
        'email': 'ivanovo@expertsmet.ru',
        'address': 'г. Иваново, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 24,
    },
    'izhevsk': {
        'name': 'Ижевск',
        'name_prep': 'Ижевске',
        'subdomain': 'izhevsk',
        'url': 'https://izhevsk.expertsmet.ru',
        'template_folder': 'izhevsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'izhevsk@expertsmet.ru',
        'address': 'г. Ижевск, ул. Примерная, д. 1',
        'timezone': 'Europe/Samara',
        'is_main': False,
        'order': 25,
    },
    'kaliningrad': {
        'name': 'Калининград',
        'name_prep': 'Калининграде',
        'subdomain': 'kaliningrad',
        'url': 'https://kaliningrad.expertsmet.ru',
        'template_folder': 'kaliningrad',
        'phone': '+7 (917) 565-46-16',
        'email': 'kaliningrad@expertsmet.ru',
        'address': 'г. Калининград, ул. Примерная, д. 1',
        'timezone': 'Europe/Kaliningrad',
        'is_main': False,
        'order': 26,
    },
    'kemerovo': {
        'name': 'Кемерово',
        'name_prep': 'Кемерове',
        'subdomain': 'kemerovo',
        'url': 'https://kemerovo.expertsmet.ru',
        'template_folder': 'kemerovo',
        'phone': '+7 (917) 565-46-16',
        'email': 'kemerovo@expertsmet.ru',
        'address': 'г. Кемерово, ул. Примерная, д. 1',
        'timezone': 'Asia/Krasnoyarsk',
        'is_main': False,
        'order': 27,
    },
    'kirov': {
        'name': 'Киров',
        'name_prep': 'Кирове',
        'subdomain': 'kirov',
        'url': 'https://kirov.expertsmet.ru',
        'template_folder': 'kirov',
        'phone': '+7 (917) 565-46-16',
        'email': 'kirov@expertsmet.ru',
        'address': 'г. Киров, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 28,
    },
    'kursk': {
        'name': 'Курск',
        'name_prep': 'Курске',
        'subdomain': 'kursk',
        'url': 'https://kursk.expertsmet.ru',
        'template_folder': 'kursk',
        'phone': '+7 (917) 565-46-16',
        'email': 'kursk@expertsmet.ru',
        'address': 'г. Курск, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 29,
    },
    'lipetsk': {
        'name': 'Липецк',
        'name_prep': 'Липецке',
        'subdomain': 'lipetsk',
        'url': 'https://lipetsk.expertsmet.ru',
        'template_folder': 'lipetsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'lipetsk@expertsmet.ru',
        'address': 'г. Липецк, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 30,
    },
    'magnitogorsk': {
        'name': 'Магнитогорск',
        'name_prep': 'Магнитогорске',
        'subdomain': 'magnitogorsk',
        'url': 'https://magnitogorsk.expertsmet.ru',
        'template_folder': 'magnitogorsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'magnitogorsk@expertsmet.ru',
        'address': 'г. Магнитогорск, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 31,
    },
    'makhachkala': {
        'name': 'Махачкала',
        'name_prep': 'Махачкале',
        'subdomain': 'makhachkala',
        'url': 'https://makhachkala.expertsmet.ru',
        'template_folder': 'makhachkala',
        'phone': '+7 (917) 565-46-16',
        'email': 'makhachkala@expertsmet.ru',
        'address': 'г. Махачкала, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 32,
    },
    'nizhny-tagil': {
        'name': 'Нижний Тагил',
        'name_prep': 'Нижнем Тагиле',
        'subdomain': 'nizhny-tagil',
        'url': 'https://nizhny-tagil.expertsmet.ru',
        'template_folder': 'nizhny-tagil',
        'phone': '+7 (917) 565-46-16',
        'email': 'nizhny-tagil@expertsmet.ru',
        'address': 'г. Нижний Тагил, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 33,
    },
    'orenburg': {
        'name': 'Оренбург',
        'name_prep': 'Оренбурге',
        'subdomain': 'orenburg',
        'url': 'https://orenburg.expertsmet.ru',
        'template_folder': 'orenburg',
        'phone': '+7 (917) 565-46-16',
        'email': 'orenburg@expertsmet.ru',
        'address': 'г. Оренбург, ул. Примерная, д. 1',
        'timezone': 'Asia/Yekaterinburg',
        'is_main': False,
        'order': 34,
    },
    'penza': {
        'name': 'Пенза',
        'name_prep': 'Пензе',
        'subdomain': 'penza',
        'url': 'https://penza.expertsmet.ru',
        'template_folder': 'penza',
        'phone': '+7 (917) 565-46-16',
        'email': 'penza@expertsmet.ru',
        'address': 'г. Пенза, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 35,
    },
    'ryazan': {
        'name': 'Рязань',
        'name_prep': 'Рязани',
        'subdomain': 'ryazan',
        'url': 'https://ryazan.expertsmet.ru',
        'template_folder': 'ryazan',
        'phone': '+7 (917) 565-46-16',
        'email': 'ryazan@expertsmet.ru',
        'address': 'г. Рязань, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 36,
    },
    'sochi': {
        'name': 'Сочи',
        'name_prep': 'Сочи',
        'subdomain': 'sochi',
        'url': 'https://sochi.expertsmet.ru',
        'template_folder': 'sochi',
        'phone': '+7 (917) 565-46-16',
        'email': 'sochi@expertsmet.ru',
        'address': 'г. Сочи, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 37,
    },
    'stavropol': {
        'name': 'Ставрополь',
        'name_prep': 'Ставрополе',
        'subdomain': 'stavropol',
        'url': 'https://stavropol.expertsmet.ru',
        'template_folder': 'stavropol',
        'phone': '+7 (917) 565-46-16',
        'email': 'stavropol@expertsmet.ru',
        'address': 'г. Ставрополь, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 38,
    },
    'tver': {
        'name': 'Тверь',
        'name_prep': 'Твери',
        'subdomain': 'tver',
        'url': 'https://tver.expertsmet.ru',
        'template_folder': 'tver',
        'phone': '+7 (917) 565-46-16',
        'email': 'tver@expertsmet.ru',
        'address': 'г. Тверь, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 39,
    },
    'tomsk': {
        'name': 'Томск',
        'name_prep': 'Томске',
        'subdomain': 'tomsk',
        'url': 'https://tomsk.expertsmet.ru',
        'template_folder': 'tomsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'tomsk@expertsmet.ru',
        'address': 'г. Томск, ул. Примерная, д. 1',
        'timezone': 'Asia/Krasnoyarsk',
        'is_main': False,
        'order': 40,
    },
    'tolyatti': {
        'name': 'Тольятти',
        'name_prep': 'Тольятти',
        'subdomain': 'tolyatti',
        'url': 'https://tolyatti.expertsmet.ru',
        'template_folder': 'tolyatti',
        'phone': '+7 (917) 565-46-16',
        'email': 'tolyatti@expertsmet.ru',
        'address': 'г. Тольятти, ул. Примерная, д. 1',
        'timezone': 'Europe/Samara',
        'is_main': False,
        'order': 41,
    },
    'ulyanovsk': {
        'name': 'Ульяновск',
        'name_prep': 'Ульяновске',
        'subdomain': 'ulyanovsk',
        'url': 'https://ulyanovsk.expertsmet.ru',
        'template_folder': 'ulyanovsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'ulyanovsk@expertsmet.ru',
        'address': 'г. Ульяновск, ул. Примерная, д. 1',
        'timezone': 'Europe/Samara',
        'is_main': False,
        'order': 42,
    },
    'cheboksary': {
        'name': 'Чебоксары',
        'name_prep': 'Чебоксарах',
        'subdomain': 'cheboksary',
        'url': 'https://cheboksary.expertsmet.ru',
        'template_folder': 'cheboksary',
        'phone': '+7 (917) 565-46-16',
        'email': 'cheboksary@expertsmet.ru',
        'address': 'г. Чебоксары, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 43,
    },
    'yaroslavl': {
        'name': 'Ярославль',
        'name_prep': 'Ярославле',
        'subdomain': 'yaroslavl',
        'url': 'https://yaroslavl.expertsmet.ru',
        'template_folder': 'yaroslavl',
        'phone': '+7 (917) 565-46-16',
        'email': 'yaroslavl@expertsmet.ru',
        'address': 'г. Ярославль, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 44,
    },
    'vladikavkaz': {
        'name': 'Владикавказ',
        'name_prep': 'Владикавказе',
        'subdomain': 'vladikavkaz',
        'url': 'https://vladikavkaz.expertsmet.ru',
        'template_folder': 'vladikavkaz',
        'phone': '+7 (917) 565-46-16',
        'email': 'vladikavkaz@expertsmet.ru',
        'address': 'г. Владикавказ, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 45,
    },
    'arkhangelsk': {
        'name': 'Архангельск',
        'name_prep': 'Архангельске',
        'subdomain': 'arkhangelsk',
        'url': 'https://arkhangelsk.expertsmet.ru',
        'template_folder': 'arkhangelsk',
        'phone': '+7 (917) 565-46-16',
        'email': 'arkhangelsk@expertsmet.ru',
        'address': 'г. Архангельск, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 46,
    },
    'astrakhan': {
        'name': 'Астрахань',
        'name_prep': 'Астрахани',
        'subdomain': 'astrakhan',
        'url': 'https://astrakhan.expertsmet.ru',
        'template_folder': 'astrakhan',
        'phone': '+7 (917) 565-46-16',
        'email': 'astrakhan@expertsmet.ru',
        'address': 'г. Астрахань, ул. Примерная, д. 1',
        'timezone': 'Europe/Samara',
        'is_main': False,
        'order': 47,
    },
    'tula': {
        'name': 'Тула',
        'name_prep': 'Туле',
        'subdomain': 'tula',
        'url': 'https://tula.expertsmet.ru',
        'template_folder': 'tula',
        'phone': '+7 (917) 565-46-16',
        'email': 'tula@expertsmet.ru',
        'address': 'г. Тула, ул. Примерная, д. 1',
        'timezone': 'Europe/Moscow',
        'is_main': False,
        'order': 48,
    },
}

# Алиасы поддоменов на канонические значения subdomain из CITIES_DATA
SUBDOMAIN_ALIASES = {
    # Частая ошибка в написании Челябинска
    'cheliabinsk': 'chelyabinsk',
    # Здесь можно добавить другие алиасы при необходимости
}

def normalize_subdomain(subdomain: str) -> str:
    """Возвращает канонический subdomain с учетом алиасов."""
    if not subdomain:
        return subdomain
    return SUBDOMAIN_ALIASES.get(subdomain, subdomain)


def get_current_city_data(request):
    """
    Определяет данные текущего города на основе поддомена
    """
    # Получаем заголовок Host из HTTP запроса
    host = request.META.get('HTTP_HOST', request.get_host())
    
    # Если это локальный хост, используем заголовок Host
    if host.startswith('127.0.0.1') or host.startswith('localhost'):
        # Ищем настоящий хост в заголовках HTTP_HOST
        actual_host = request.META.get('HTTP_HOST', host)
        if actual_host.startswith('127.0.0.1') or actual_host.startswith('localhost'):
            # Если всё ещё localhost, по умолчанию москва
            subdomain = 'moscow'
        else:
            subdomain = actual_host.split('.')[0] if '.' in actual_host else 'moscow'
    else:
        subdomain = host.split('.')[0] if '.' in host else 'moscow'
    
    # Если основной домен или www, не подставляем город
    if subdomain in ['expertsmet', 'www', '127', 'localhost']:
        return None
    
    # Нормализуем поддомен по алиасам
    normalized = normalize_subdomain(subdomain)

    # Поиск города по поддомену
    for city_key, city_data in CITIES_DATA.items():
        if city_data['subdomain'] == normalized:
            return city_data
    
    # По умолчанию возвращаем Москву
    return CITIES_DATA['moscow']


def get_all_cities():
    """
    Возвращает все города отсортированные по порядку для модального окна
    """
    return sorted(CITIES_DATA.values(), key=lambda x: x['order'])


def get_city_by_key(city_key):
    """
    Получить данные города по ключу
    """
    return CITIES_DATA.get(city_key)

def get_city_by_subdomain(subdomain):
    """Находит город по subdomain (с учетом алиасов)."""
    sub = normalize_subdomain(subdomain)
    for city_key, city_data in CITIES_DATA.items():
        if city_data.get('subdomain') == sub:
            return city_data
    return None

def get_city_key_by_subdomain(subdomain):
    """Возвращает ключ города по subdomain (с учетом алиасов)."""
    sub = normalize_subdomain(subdomain)
    for city_key, city_data in CITIES_DATA.items():
        if city_data.get('subdomain') == sub:
            return city_key
    return None


def get_city_template_path(city_data):
    """
    Формирует путь к шаблону города
    """
    return f"main/city/{city_data['template_folder']}/index.html"


def city_exists_in_config(subdomain):
    """Проверяет существование города по subdomain (учитывая алиасы)."""
    return get_city_key_by_subdomain(subdomain) is not None
